//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILayerAB_WebService")]
public interface ILayerAB_WebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayerAB_WebService/ProcessVideo", ReplyAction="http://tempuri.org/ILayerAB_WebService/ProcessVideoResponse")]
    string ProcessVideo(string videoKeyname, bool search, bool onDemand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayerAB_WebService/ProcessVideo", ReplyAction="http://tempuri.org/ILayerAB_WebService/ProcessVideoResponse")]
    System.Threading.Tasks.Task<string> ProcessVideoAsync(string videoKeyname, bool search, bool onDemand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayerAB_WebService/EnablePolledProcessing", ReplyAction="http://tempuri.org/ILayerAB_WebService/EnablePolledProcessingResponse")]
    string EnablePolledProcessing(int pollingInterval, string searchServerEndpoint);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayerAB_WebService/EnablePolledProcessing", ReplyAction="http://tempuri.org/ILayerAB_WebService/EnablePolledProcessingResponse")]
    System.Threading.Tasks.Task<string> EnablePolledProcessingAsync(int pollingInterval, string searchServerEndpoint);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayerAB_WebService/DisablePolledProcessing", ReplyAction="http://tempuri.org/ILayerAB_WebService/DisablePolledProcessingResponse")]
    string DisablePolledProcessing();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayerAB_WebService/DisablePolledProcessing", ReplyAction="http://tempuri.org/ILayerAB_WebService/DisablePolledProcessingResponse")]
    System.Threading.Tasks.Task<string> DisablePolledProcessingAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILayerAB_WebServiceChannel : ILayerAB_WebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LayerAB_WebServiceClient : System.ServiceModel.ClientBase<ILayerAB_WebService>, ILayerAB_WebService
{
    
    public LayerAB_WebServiceClient()
    {
    }
    
    public LayerAB_WebServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LayerAB_WebServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LayerAB_WebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LayerAB_WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ProcessVideo(string videoKeyname, bool search, bool onDemand)
    {
        return base.Channel.ProcessVideo(videoKeyname, search, onDemand);
    }
    
    public System.Threading.Tasks.Task<string> ProcessVideoAsync(string videoKeyname, bool search, bool onDemand)
    {
        return base.Channel.ProcessVideoAsync(videoKeyname, search, onDemand);
    }
    
    public string EnablePolledProcessing(int pollingInterval, string searchServerEndpoint)
    {
        return base.Channel.EnablePolledProcessing(pollingInterval, searchServerEndpoint);
    }
    
    public System.Threading.Tasks.Task<string> EnablePolledProcessingAsync(int pollingInterval, string searchServerEndpoint)
    {
        return base.Channel.EnablePolledProcessingAsync(pollingInterval, searchServerEndpoint);
    }
    
    public string DisablePolledProcessing()
    {
        return base.Channel.DisablePolledProcessing();
    }
    
    public System.Threading.Tasks.Task<string> DisablePolledProcessingAsync()
    {
        return base.Channel.DisablePolledProcessingAsync();
    }
}
